name: 'purge-workflow-runs'
description: 'action to purge workflow runs'
author: 'Jonas Strassel'
inputs:
  token:
    required: true
    description: "token.."
  days-old:
    required: false
    description: 'least days the runs have to be old to get purged'
    default: '30'
runs:
  using: 'node12'
  main: 'dist/index.js'
